name: Notify Slack on PR Comments

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request && (
        contains(github.event.issue.user.login, 'your-username') ||
        contains(join(github.event.issue.assignees.*.login, ','), 'your-username') ||
        contains(github.event.comment.body, 'your-username')
      )
    steps:
      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "New comment on a PR you're involved in: <${{ github.event.comment.html_url }}|View Comment>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
