name: Notify Slack on PR Comments (Includes Self-Comments for Testing)

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: |
      (
        # Condition for regular PR comments (issue_comment trigger)
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.issue.user.login == 'everettbergeson'
        # Note: Checking if you are a reviewer here is complex without an API call
      ) ||
      (
        # Condition for review comments (pull_request_review_comment trigger)
        github.event_name == 'pull_request_review_comment' && (
          github.event.pull_request.user.login == 'your-github-username' ||
          contains(github.event.pull_request.requested_reviewers.*.login, 'your-github-username')
        )
      )
    steps:
      - name: Send to Slack
        uses: slackapi/slack-github-action@v1.24.0 # Or latest version
        with:
          payload: |
            {
              "text": "[TEST] New comment on PR <${{ github.event.issue.html_url || github.event.pull_request.html_url }}|#${{ github.event.issue.number || github.event.pull_request.number }}>: <${{ github.event.comment.html_url }}|View Comment>\nAuthor: ${{ github.event.comment.user.login }}\nComment: ${{ github.event.comment.body }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}